First review - Danna Shirley
GenesysCloudBlueprints/microsoft-teams-blueprint pull request #4
Opened 2021-06-01 13:37 UTC by shansrini

Hi Danna,

Updated the blueprint to the template and the graphics. Let me know your comments and suggestions if any.

2021-06-01 17:48 UTC, DannaShirley requested changes
I stopped editing b/c most of my comments were similar in nature. I'd like to see this again when you have a chance to work through them. Thank you!

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
>  ---
"The call can be either inbound or outbound...

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +The following illustration shows the meeting scheduling solution from an agent’s point of view.
Same as above

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +To enable an agent to use Microsoft Teams meeting from Genesys Cloud, the operation spans multiple platforms at the system level. Genesys Cloud and Microsoft Graph offer public APIs that provide this
Simplify and avoid the use of the term, "interaction" since it is a reserved term in Genesys Cloud. Example: 

"To enable an agent to use Microsoft Teams from their Genesys Cloud agent UI, you use several public APIs that are available from Genesys Cloud and Microsoft Graph. The following illustration shows the API calls..."

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +* [Solution components](#solution-components)
Global request: add alt-text to all links and graphics. Like this: 
[Solution components](#solution-components "Goes to the Solution components section"

I did not mark subsequent instances. Please update all links and graphics for accessibility compliance.

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +![Microsoft Teams Integration](images/microsoft-teams-architect.png)
* Use sentence case for titles, headings, labels, etc.
* Add accessibility text 
Example:  
[Microsoft Teams integration](images/microsoft-teams-architect.png "Microsoft Teams integration)

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +  - [Load Supporting Data Actions](#load-supporting-data-actions)
Caps style: "Load supporting data actions"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +  - [Import Create Teams Video Meeting data action](#import-create-teams-video-meeting-data-action)
Article missing? "Import the Create Teams Video Meeting data action")

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +  - [Send SMS data action](#send-sms-data-action)
Article missing? "Send the..."

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +  - [Load Script](#load-script)
Caps style. Article missing? "Load the script"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +### Configure Microsoft Azure custom app
Article missing. "Configure the Microsoft Azure custom app"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +2. Navigate to **App registrations**, and click **New registration**.
Serial comma is not needed in a list of only 2 items. "Navigate to **App registrations** and click **New registration**."

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> -3. View the new application. Copy the Application and Directory IDs for later use.
Use lowercase for "application" and "directory"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +4. On the application's Overview page, copy **Application (client) ID** and **Directory (tenant) ID** for later use.
Bold for page titles. "Overview"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +   **Note:** You cannot view or retrieve the client secret value later.
Use standard note formatting.  
:::primary
**Note**:
note text here
:::

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +   ![Copy and save client secret](images/0ECopyClientSecret.png)
Missing article? "Copy and save the client secret"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +7. Check your Genesys Cloud permission created in Azure.
"Verify that your Genesys Cloud permission exists in Azure"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +1. Install the **Web Services Data Actions** integration from Genesys Cloud or from the AppFoundry. See [About the data actions integrations](https://help.mypurecloud.com/?p=209478 "Opens the Data Ac
I searched for "Web Services Data Actions integration" in the App Foundry and could not find it. Please verify this step.  https://appfoundry.genesys.com/

If this is not a pre-packed/properly named integration, then do not capitalize references to it. "Install a "web services data actions integration..."

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +   ![Web Services Data Actions in Genesys Cloud Integrations Search](images/1AWebServicesDataActionInstall.png)
Caps style

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +   ![Rename and describe the Web Services Data Action](images/1BRenameWebServicesDataAction.png)
Caps style

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +5. Import authentication data action
Missing article: "Import the authentication data action"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +   The authentication data action is imported into another data action. When you add a new web services data actions integration within an organization, a Custom Auth data action is created automatic
I'm not sure why a dev needs to know about the first sentence. I'd remove, "The authentication data action is imported into another data action," unless the developer can clarify why it is significant to point out here.

Caps style: "custom auth data action"

2021-06-01 17:48 UTC, DannaShirley commented on blueprint/index.md
> +   ![Custom Auth Data Action associated with Web Services Data Actions Integration](images/1ECustomAuthDataAction.png)
Caps style. In Genesys Cloud, we avoid title caps. Here are the full details: https://intranet.genesys.com/display/PureCloud/Doc+standards%3A+Capitalization

2021-07-27 14:18 UTC, merged

2021-07-28 13:11 UTC, timsmithgenesys commented on blueprint/index.md
> +author: {author name}
This isn't valid and broke the build. Please ensure actual values are used in the future.